# Generated by Django 5.0.6 on 2024-07-03 15:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_donaciones_donar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inicio",
            name="imagen",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
