# Generated by Django 5.0.6 on 2024-07-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_inicio_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inicio",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="noticias/"),
        ),
    ]
