# Generated by Django 5.0.6 on 2024-07-12 13:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_rename_mensaje_inicio_bienvenida_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividades",
            name="publicado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="articulos",
            name="publicado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="donaciones",
            name="publicado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="donacionescbu",
            name="publicado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historias",
            name="publicado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nosotros",
            name="publicado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="programas",
            name="publicado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="inicio",
            name="bienvenida",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="inicio",
            name="que_ofrecemos",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
