# Generated by Django 4.2.4 on 2024-09-02 13:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_remove_inicio_imagen_imagenanimada"),
    ]

    operations = [
        migrations.CreateModel(
            name="InicioSubPuntos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_punto", ckeditor.fields.RichTextField()),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "inicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_puntos",
                        to="core.inicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subpunto de Inicio",
                "verbose_name_plural": "Subpuntos de Inicio",
                "ordering": ["orden"],
            },
        ),
    ]
