# Generated by Django 4.2.4 on 2024-09-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_iniciosubpuntos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="iniciosubpuntos",
            old_name="sub_punto",
            new_name="sub_punto_parrafo",
        ),
        migrations.AddField(
            model_name="iniciosubpuntos",
            name="sub_punto_titulo",
            field=models.CharField(default="titulo", max_length=200),
        ),
    ]
