# Generated by Django 4.2.4 on 2024-09-02 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_rename_sub_punto_iniciosubpuntos_sub_punto_parrafo_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImagenAnimada",
        ),
    ]
