# Generated by Django 4.2.4 on 2024-09-02 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_delete_imagenanimada"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagenAnimada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="inicio/animated/")),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "inicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes_animadas",
                        to="core.inicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen Animada",
                "verbose_name_plural": "Imágenes Animadas",
                "ordering": ["orden"],
            },
        ),
    ]
