# Generated by Django 4.2.4 on 2024-10-01 19:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_imagenanimada"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nosotros",
            name="contenido",
        ),
        migrations.RemoveField(
            model_name="nosotros",
            name="mision",
        ),
        migrations.CreateModel(
            name="NosotrosSubPuntos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sub_punto_titulo",
                    models.CharField(default="titulo", max_length=200),
                ),
                ("sub_punto_parrafo", ckeditor.fields.RichTextField()),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "inicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_puntos",
                        to="core.nosotros",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subpunto de Nosotros",
                "verbose_name_plural": "Subpuntos de Nosotros",
                "ordering": ["orden"],
            },
        ),
    ]
