# Generated by Django 4.2.4 on 2024-10-01 20:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_nosotrosquebuscamos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nosotros",
            options={
                "verbose_name": "Sobre Nosotras",
                "verbose_name_plural": "Sobre Nosotras",
            },
        ),
        migrations.AddField(
            model_name="nosotrosquebuscamos",
            name="campo_texto",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
