# Generated by Django 4.2.4 on 2024-10-10 12:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_remove_inicio_bienvenida_inicio_mision"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actividades",
            name="info",
        ),
        migrations.AddField(
            model_name="actividades",
            name="horario",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="actividades",
            name="imagen_actividad",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="actividades",
            name="info_detalle",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="actividades",
            name="descripcion",
            field=models.TextField(null=True),
        ),
    ]
